# Generated by Django 2.1.4 on 2020-05-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('image_uri', models.CharField(max_length=50)),
                ('playlist', models.CharField(max_length=50)),
            ],
        ),
    ]
